[package]
name = "image_renamer"
version = "0.1.0"
edition = "2021"
authors = ["Krešimir Bruner <kresimir.bruner@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.5"